version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Print system date
          shell: /bin/sh
          command: date
      - run:
          name: Print info
          shell: /bin/sh
          command: |
            pwd
            ls -la
            cat /etc/*-release
